# Generated by Django 2.0 on 2019-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='locked_thread_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
