# Generated by Django 2.0 on 2019-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_notify_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
