# Generated by Django 2.0 on 2019-06-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190521_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disable_balance_warning_emails',
            field=models.BooleanField(default=False),
        ),
    ]
