# Generated by Django 2.0 on 2019-04-12 18:31

import tritium.apps.model_base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERC20',
            fields=[
                ('id', models.CharField(default=tritium.apps.model_base.cutePk, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(max_length=16)),
                ('decimal_places', models.PositiveIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.Contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
