# Generated by Django 2.0 on 2019-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_erc20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erc20',
            name='symbol',
            field=models.CharField(max_length=64),
        ),
    ]
