# Generated by Django 2.0 on 2019-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_specific_contract_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='abi_methods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
