# Generated by Django 2.0 on 2019-05-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='summary_notifications',
            new_name='daily_notifications',
        ),
        migrations.AddField(
            model_name='subscription',
            name='monthly_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
