# Generated by Django 2.0 on 2019-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20190523_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='weekly_emails',
            field=models.BooleanField(default=False),
        ),
    ]
